name: local_courses
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  resizable_widget: ^1.0.5



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    
  fonts:
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Nunito-Regular.ttf